### ISSUE TITLE
Allow attributes to the middle of a macro chain?

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetML#35]
Do we want to continue to allow one to add attributes to the middle of a macro chain?

This DoenetML currently works by creating a line with a modified slope of 3, extracting its second point and then changing its y-coordinate to 2.

```
<line name="l" />
$l{slope="3"}.points[2]{y="2"}
```

If we didn't allow one change to add attributes in the middle of the attribute chain, then we wouldn't need to create the intermediate construction of a line with slope of 3 and could just grab the second point of the line. It would also reduce complexity in macros if one could only add attributes at the end.

**Comment by siefkenj** [comment]
The new macro parser assumes attributes only occur one time, at the end of a macro.

**Comment by dqnykamp** [comment]
Right. It looks like we resolved this question.
