### ISSUE TITLE
Code editor tabbing and Pretty Print tabbing are inconsistent

### ISSUE THREAD

**Issue by dqnykamp** [Doenet/DoenetML#43]
The built in tabbing for `<codeEditor>` is 2 spaces, but the tabbing for Pretty Print is 4 spaces. So, if I type `<graph>{enter}<line />{enter}</graph>`, the result is formatted with 2 spaces as
```
<graph>
  <line />
</graph>
```
Subsequently clicking Pretty Print, reformats to 4 spaces as
```
<graph>
    <line />
</graph>
```
Also, pressing tab in the `<codeEditor>` adds 2 spaces, consistent with it autoformat behavior.

**Comment by siefkenj** [comment]
Sure. I can change it to 2 spaces by default (even though I think 4 is much easier to read...)

**Comment by siefkenj** [comment]
Fixed in #24
